version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "setup git"
          command: |
            git config user.email "circleci"
            git config user.name "circleci"
      - run:
          name: "get version"
          command: export VERSION=cat VERSION
      - run:
          name: "update version"
          command: VERSION="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))" && git commit -am "update version ${VERSION}" && git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com//zacharyhooker/CCITests.git master
