version: 2
jobs:
  build:
    docker:
      -image: circleci/node
    steps:
      - checkout
      - run: VERSION=cat VERSION
      - run: VERSION="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))" && git commit -am "update version ${VERSION}" && git push
