version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "setup git"
          command: |
            git config user.email "circleci"
            git config user.name "circleci"
      - run:
          name: "get version"
          command: export VERSION=`cat VERSION`
      - run:
          name: "update version"
          command: if [[ "$VERSION" =~ (.*[^0-9])([0-9]+)$ ]] ; then VERSION="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))" && echo "$VERSION" > VERSION; fi 
      - run:
          name: "git commit"
          command:  git commit -am "update version ${VERSION} [ci skip]" && git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/zacharyhooker/CCITests.git master
